import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'AI-Generated Content Disclosure',
  description: 'AI-generated content disclosure and legal disclaimer for Resolvaio.',
};

export default function AIDisclosurePage() {
  return (
    <main className="min-h-screen bg-[#F7F7F5] px-6 py-20">
      <div className="mx-auto max-w-2xl">
        <Link
          href="/"
          className="text-[13px] text-[#8A8A8A] transition-colors hover:text-[#111]"
        >
          Back to home
        </Link>

        <h1 className="mt-8 text-[32px] font-semibold tracking-tight text-[#111]">
          AI-Generated Content Disclosure
        </h1>
        <p className="mt-2 text-[13px] text-[#8A8A8A]">
          Effective Date: May 28, 2026 &middot; Last Updated: May 28, 2026
        </p>

        <div className="mt-10 space-y-8 text-[15px] leading-[1.7] text-[#5F5F5F]">
          {/* ---------------------------------------------------------- */}
          {/*  What Resolvaio Is                                         */}
          {/* ---------------------------------------------------------- */}
          <section>
            <h2 className="text-[20px] font-semibold text-[#111]">
              What Resolvaio Is
            </h2>
            <p>
              Resolvaio is a{' '}
              <strong className="text-[#111]">writing assistance tool</strong>{' '}
              that uses artificial intelligence to help you draft demand letters
              and cancellation emails. Every document generated through our
              Service is created by AI models (powered by OpenAI) using your
              case information and our knowledge base of verified consumer
              protection statutes.
            </p>
          </section>

          {/* ---------------------------------------------------------- */}
          {/*  What Resolvaio Is Not                                     */}
          {/* ---------------------------------------------------------- */}
          <section>
            <h2 className="text-[20px] font-semibold text-[#111]">
              What Resolvaio Is Not
            </h2>
            <p>
              Resolvaio is <strong className="text-[#111]">not</strong>:
            </p>
            <ul className="mt-2 list-disc space-y-2.5 pl-6">
              <li>
                <strong className="text-[#111]">A law firm</strong> &mdash; we
                are not licensed to practice law in any jurisdiction
              </li>
              <li>
                <strong className="text-[#111]">A legal advisor</strong> &mdash;
                we do not provide legal advice, evaluate whether you have a
                valid claim, or assess the strength of your case
              </li>
              <li>
                <strong className="text-[#111]">A lawyer or attorney</strong>{' '}
                &mdash; use of the Service does not create an attorney-client
                relationship
              </li>
              <li>
                <strong className="text-[#111]">A guarantee of outcomes</strong>{' '}
                &mdash; we do not predict, promise, or guarantee any result from
                sending letters or emails generated by the Service
              </li>
              <li>
                <strong className="text-[#111]">
                  A substitute for professional legal counsel
                </strong>{' '}
                &mdash; if your dispute involves legal complexity, adversarial
                counsel, or potential litigation, you should consult a licensed
                attorney
              </li>
            </ul>
          </section>

          {/* ---------------------------------------------------------- */}
          {/*  How AI Generation Works                                   */}
          {/* ---------------------------------------------------------- */}
          <section>
            <h2 className="text-[20px] font-semibold text-[#111]">
              How AI Generation Works
            </h2>
            <ol className="list-decimal space-y-2.5 pl-6">
              <li>
                <strong className="text-[#111]">Diagnostic:</strong> You answer
                questions about your dispute. We use your answers to identify
                your jurisdiction and applicable statutes.
              </li>
              <li>
                <strong className="text-[#111]">Document extraction:</strong> If
                you upload documents (leases, billing statements, photos), AI
                vision extracts relevant data points such as amounts, dates, and
                line items.
              </li>
              <li>
                <strong className="text-[#111]">Grounding:</strong> We assemble
                a context package of verified statutes, deadlines, and
                procedural information from our knowledge base for your specific
                jurisdiction.
              </li>
              <li>
                <strong className="text-[#111]">Generation:</strong> An AI model
                generates your letter or email sequence, citing only sources
                from the grounding context.
              </li>
              <li>
                <strong className="text-[#111]">Validation:</strong>{' '}
                Post-generation, we validate citations against our knowledge
                base and strip any ungrounded references. A compliance scan
                checks for prohibited language.
              </li>
            </ol>
          </section>

          {/* ---------------------------------------------------------- */}
          {/*  Limitations of AI                                         */}
          {/* ---------------------------------------------------------- */}
          <section>
            <h2 className="text-[20px] font-semibold text-[#111]">
              Limitations of AI-Generated Content
            </h2>
            <p>
              Despite our citation validation and compliance scanning process,
              AI-generated content has inherent limitations:
            </p>
            <ul className="mt-2 list-disc space-y-2.5 pl-6">
              <li>
                <strong className="text-[#111]">Statutes change.</strong> Laws
                are amended, repealed, or reinterpreted. While we maintain and
                update our knowledge base, there may be a lag between a legal
                change and our update.
              </li>
              <li>
                <strong className="text-[#111]">
                  AI may misinterpret your situation.
                </strong>{' '}
                The AI generates content based on the information you provide.
                If your inputs are incomplete or ambiguous, the output may not
                fully address your circumstances.
              </li>
              <li>
                <strong className="text-[#111]">
                  AI may produce errors.
                </strong>{' '}
                Despite validation, AI-generated text may contain factual
                inaccuracies, formatting errors, or misapplied legal references.
              </li>
              <li>
                <strong className="text-[#111]">
                  Every dispute is unique.
                </strong>{' '}
                Generated letters are based on how similar disputes are
                typically handled. Your specific facts, evidence, and
                circumstances may require a different approach.
              </li>
            </ul>
          </section>

          {/* ---------------------------------------------------------- */}
          {/*  Your Responsibilities                                     */}
          {/* ---------------------------------------------------------- */}
          <section>
            <h2 className="text-[20px] font-semibold text-[#111]">
              Your Responsibilities
            </h2>
            <p>Before sending any generated document, you should:</p>
            <ul className="mt-2 list-disc space-y-2.5 pl-6">
              <li>
                <strong className="text-[#111]">
                  Review the entire document carefully
                </strong>{' '}
                for accuracy, completeness, and appropriateness to your specific
                situation
              </li>
              <li>
                <strong className="text-[#111]">
                  Verify all legal citations
                </strong>{' '}
                with official sources (state legislature websites, court
                websites) before relying on them
              </li>
              <li>
                <strong className="text-[#111]">
                  Ensure all factual statements are accurate
                </strong>{' '}
                &mdash; you are responsible for the truthfulness of information
                in letters you send
              </li>
              <li>
                <strong className="text-[#111]">
                  Consider consulting a licensed attorney
                </strong>{' '}
                if you have questions about your rights, your claim, or the
                appropriate course of action
              </li>
              <li>
                <strong className="text-[#111]">
                  Stop and seek legal counsel
                </strong>{' '}
                if the other party responds with legal representation or threats
                of legal action
              </li>
            </ul>
          </section>

          {/* ---------------------------------------------------------- */}
          {/*  Data Handling                                             */}
          {/* ---------------------------------------------------------- */}
          <section>
            <h2 className="text-[20px] font-semibold text-[#111]">
              AI Data Handling
            </h2>
            <p>
              We use OpenAI&rsquo;s API with{' '}
              <strong className="text-[#111]">zero data retention</strong>{' '}
              enabled. This means:
            </p>
            <ul className="mt-2 list-disc space-y-1.5 pl-6">
              <li>OpenAI does not store your case data or document contents after processing</li>
              <li>Your data is not used to train OpenAI&rsquo;s models</li>
              <li>Each generation request is processed and discarded</li>
            </ul>
            <p className="mt-3">
              For full details on how we handle your data, see our{' '}
              <Link
                href="/legal/privacy"
                className="text-[#111] underline underline-offset-4"
              >
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          {/* ---------------------------------------------------------- */}
          {/*  Adversarial Counsel                                       */}
          {/* ---------------------------------------------------------- */}
          <section>
            <h2 className="text-[20px] font-semibold text-[#111]">
              When We Stop Generating
            </h2>
            <p>
              If the other party in your dispute retains legal counsel or
              threatens legal action, the Service will stop generating content
              for that case. This is by design. At that point, your dispute has
              escalated beyond the scope of a writing assistance tool, and you
              should consult with a licensed attorney. We can provide state bar
              referral links to help you find one.
            </p>
          </section>

          {/* ---------------------------------------------------------- */}
          {/*  Contact                                                   */}
          {/* ---------------------------------------------------------- */}
          <section>
            <h2 className="text-[20px] font-semibold text-[#111]">
              Questions
            </h2>
            <p>
              Questions about how AI is used in the Service? Email{' '}
              <a
                href="mailto:support@resolvaio.com"
                className="text-[#111] underline underline-offset-4"
              >
                support@resolvaio.com
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-16 border-t border-[#E8E8E5] pt-8 text-center">
          <div className="flex flex-wrap justify-center gap-x-4 gap-y-1 text-[12px] text-[#8A8A8A]">
            <Link href="/legal/terms" className="transition-colors hover:text-[#111]">Terms</Link>
            <Link href="/legal/privacy" className="transition-colors hover:text-[#111]">Privacy</Link>
            <Link href="/legal/cookies" className="transition-colors hover:text-[#111]">Cookies</Link>
            <Link href="/legal/acceptable-use" className="transition-colors hover:text-[#111]">Acceptable Use</Link>
            <Link href="/legal/accessibility" className="transition-colors hover:text-[#111]">Accessibility</Link>
          </div>
          <p className="mt-4 text-[12px] text-[#8A8A8A]">
            &copy; {new Date().getFullYear()} Resolvaio. All rights reserved.
            Resolvaio is owned and operated by Nikola Innovations Limited.
          </p>
        </div>
      </div>
    </main>
  );
}
