/**
 * State resources for unsupported jurisdictions.
 *
 * Mirrors kb/unsupported/state-resources/index.json but lives inside
 * src/ so TypeScript can resolve it. This is the client-safe export.
 *
 * When adding a new state to the supported deposit list, remove it
 * from this map (it will use the full generation pipeline instead).
 */

/* ------------------------------------------------------------------ */
/*  Types                                                             */
/* ------------------------------------------------------------------ */

export interface StateResourceEntry {
  name: string;
  deposit_statute: string;
  deposit_statute_url: string;
  small_claims_url: string;
  legal_aid_url: string;
  ag_complaint_url: string;
}

/* ------------------------------------------------------------------ */
/*  Data (sourced from kb/unsupported/state-resources/index.json)     */
/* ------------------------------------------------------------------ */

export const STATE_RESOURCES: Record<string, StateResourceEntry> = {
  AL: { name: 'Alabama', deposit_statute: 'Ala. Code §35-9A-201', deposit_statute_url: 'https://www.legislature.state.al.us/aliswww/ISD/ALCode1975/35/9A/35-9A-201.htm', small_claims_url: 'https://www.alacourt.gov/SmallClaims.aspx', legal_aid_url: 'https://www.legalservicesalabama.org/', ag_complaint_url: 'https://www.alabamaag.gov/consumer-protection/file-complaint/' },
  AK: { name: 'Alaska', deposit_statute: 'Alaska Stat. §34.03.070', deposit_statute_url: 'https://www.akleg.gov/basis/statutes.asp#34.03.070', small_claims_url: 'https://courts.alaska.gov/shc/smallclaims/', legal_aid_url: 'https://alsc-law.org/', ag_complaint_url: 'https://law.alaska.gov/department/civil/consumer/complaint.html' },
  AZ: { name: 'Arizona', deposit_statute: 'Ariz. Rev. Stat. §33-1321', deposit_statute_url: 'https://www.azleg.gov/ars/33/01321.htm', small_claims_url: 'https://www.azcourts.gov/selfservicecenter/Small-Claims', legal_aid_url: 'https://www.azlawhelp.org/', ag_complaint_url: 'https://www.azag.gov/complaints/consumer' },
  AR: { name: 'Arkansas', deposit_statute: 'Ark. Code §18-16-304', deposit_statute_url: 'https://www.arkleg.state.ar.us/', small_claims_url: 'https://www.arcourts.gov/', legal_aid_url: 'https://arlegalaid.org/', ag_complaint_url: 'https://arkansasag.gov/consumer-protection/file-a-complaint/' },
  CO: { name: 'Colorado', deposit_statute: 'Colo. Rev. Stat. §38-12-103', deposit_statute_url: 'https://leg.colorado.gov/', small_claims_url: 'https://www.courts.state.co.us/Self_Help/smallclaims/', legal_aid_url: 'https://www.coloradolegalservices.org/', ag_complaint_url: 'https://coag.gov/file-complaint/' },
  CT: { name: 'Connecticut', deposit_statute: 'Conn. Gen. Stat. §47a-21', deposit_statute_url: 'https://www.cga.ct.gov/current/pub/chap_830.htm#sec_47a-21', small_claims_url: 'https://www.jud.ct.gov/lawlib/law/smallclaims.htm', legal_aid_url: 'https://ctlawhelp.org/', ag_complaint_url: 'https://www.dir.ct.gov/ag/complaint/' },
  DC: { name: 'District of Columbia', deposit_statute: 'D.C. Code §42-3502.17', deposit_statute_url: 'https://code.dccouncil.gov/', small_claims_url: 'https://www.dccourts.gov/services/small-claims-matters', legal_aid_url: 'https://www.lawhelp.org/dc/', ag_complaint_url: 'https://oag.dc.gov/consumer-protection/file-consumer-complaint' },
  DE: { name: 'Delaware', deposit_statute: 'Del. Code tit. 25, §5514', deposit_statute_url: 'https://delcode.delaware.gov/title25/c055/sc01/index.html', small_claims_url: 'https://courts.delaware.gov/jpcourt/', legal_aid_url: 'https://www.declasi.org/', ag_complaint_url: 'https://attorneygeneral.delaware.gov/fraud/cpu/complaint/' },
  GA: { name: 'Georgia', deposit_statute: 'Ga. Code §44-7-30 to 44-7-37', deposit_statute_url: 'https://www.legis.ga.gov/', small_claims_url: 'https://georgiacourts.gov/magistrate-court/', legal_aid_url: 'https://www.glsp.org/', ag_complaint_url: 'https://consumer.georgia.gov/resolve-your-complaint/file-complaint' },
  HI: { name: 'Hawaii', deposit_statute: 'Haw. Rev. Stat. §521-44', deposit_statute_url: 'https://www.capitol.hawaii.gov/', small_claims_url: 'https://www.courts.state.hi.us/self-help/small_claims/small_claims', legal_aid_url: 'https://www.legalaidhawaii.org/', ag_complaint_url: 'https://ag.hawaii.gov/consumer-protection/file-a-complaint/' },
  ID: { name: 'Idaho', deposit_statute: 'Idaho Code §6-321', deposit_statute_url: 'https://legislature.idaho.gov/', small_claims_url: 'https://isc.idaho.gov/small-claims', legal_aid_url: 'https://www.idaholegalaid.org/', ag_complaint_url: 'https://www.ag.idaho.gov/consumer-protection/consumer-complaints/' },
  IL: { name: 'Illinois', deposit_statute: '765 ILCS 710', deposit_statute_url: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=2204', small_claims_url: 'https://www.illinoiscourts.gov/self-help/small-claims/', legal_aid_url: 'https://www.illinoislegalaid.org/', ag_complaint_url: 'https://www.illinoisattorneygeneral.gov/consumers/filecomplaint.html' },
  IN: { name: 'Indiana', deposit_statute: 'Ind. Code §32-31-3', deposit_statute_url: 'https://iga.in.gov/', small_claims_url: 'https://www.in.gov/courts/selfservice/small-claims/', legal_aid_url: 'https://www.indianalegalservices.org/', ag_complaint_url: 'https://www.in.gov/attorneygeneral/consumer-protection-division/file-a-complaint/' },
  IA: { name: 'Iowa', deposit_statute: 'Iowa Code §562A.12', deposit_statute_url: 'https://www.legis.iowa.gov/', small_claims_url: 'https://www.iowacourts.gov/', legal_aid_url: 'https://www.iowalegalaid.org/', ag_complaint_url: 'https://www.iowaattorneygeneral.gov/' },
  KS: { name: 'Kansas', deposit_statute: 'Kan. Stat. §58-2550', deposit_statute_url: 'https://www.kslegislature.org/', small_claims_url: 'https://www.kscourts.org/Public/Small-Claims', legal_aid_url: 'https://www.kansaslegalservices.org/', ag_complaint_url: 'https://ag.ks.gov/' },
  KY: { name: 'Kentucky', deposit_statute: 'Ky. Rev. Stat. §383.580', deposit_statute_url: 'https://apps.legislature.ky.gov/', small_claims_url: 'https://kycourts.gov/', legal_aid_url: 'https://www.klaid.org/', ag_complaint_url: 'https://www.ag.ky.gov/' },
  LA: { name: 'Louisiana', deposit_statute: 'La. Rev. Stat. §9:3251-9:3254', deposit_statute_url: 'https://www.legis.la.gov/', small_claims_url: 'https://www.lasc.org/', legal_aid_url: 'https://www.la-law.org/', ag_complaint_url: 'https://www.ag.state.la.us/ConsumerComplaints' },
  ME: { name: 'Maine', deposit_statute: 'Me. Rev. Stat. tit. 14, §6031-6038', deposit_statute_url: 'https://legislature.maine.gov/', small_claims_url: 'https://www.courts.maine.gov/', legal_aid_url: 'https://www.ptla.org/', ag_complaint_url: 'https://www.maine.gov/ag/consumer/complaints/' },
  MD: { name: 'Maryland', deposit_statute: 'Md. Code, Real Prop. §8-203', deposit_statute_url: 'https://mgaleg.maryland.gov/', small_claims_url: 'https://www.mdcourts.gov/legalhelp/smallclaims', legal_aid_url: 'https://www.mdlab.org/', ag_complaint_url: 'https://www.marylandattorneygeneral.gov/' },
  MA: { name: 'Massachusetts', deposit_statute: 'Mass. Gen. Laws ch. 186, §15B', deposit_statute_url: 'https://malegislature.gov/', small_claims_url: 'https://www.mass.gov/small-claims', legal_aid_url: 'https://www.masslegalhelp.org/', ag_complaint_url: 'https://www.mass.gov/how-to/file-a-consumer-complaint' },
  MI: { name: 'Michigan', deposit_statute: 'Mich. Comp. Laws §554.601-554.616', deposit_statute_url: 'https://www.legislature.mi.gov/', small_claims_url: 'https://www.courts.michigan.gov/self-help/small-claims/', legal_aid_url: 'https://michiganlegalhelp.org/', ag_complaint_url: 'https://www.michigan.gov/ag/consumer-protection/consumer-complaints' },
  MN: { name: 'Minnesota', deposit_statute: 'Minn. Stat. §504B.178', deposit_statute_url: 'https://www.revisor.mn.gov/statutes/cite/504B.178', small_claims_url: 'https://www.mncourts.gov/', legal_aid_url: 'https://www.lawhelpmn.org/', ag_complaint_url: 'https://www.ag.state.mn.us/' },
  MS: { name: 'Mississippi', deposit_statute: 'Miss. Code §89-8-21', deposit_statute_url: 'https://www.sos.ms.gov/', small_claims_url: 'https://courts.ms.gov/', legal_aid_url: 'https://www.mslegalservices.org/', ag_complaint_url: 'https://www.ago.state.ms.us/' },
  MO: { name: 'Missouri', deposit_statute: 'Mo. Rev. Stat. §535.300', deposit_statute_url: 'https://revisor.mo.gov/', small_claims_url: 'https://www.courts.mo.gov/', legal_aid_url: 'https://www.lsmo.org/', ag_complaint_url: 'https://ago.mo.gov/' },
  MT: { name: 'Montana', deposit_statute: 'Mont. Code §70-25-201 to 70-25-206', deposit_statute_url: 'https://leg.mt.gov/', small_claims_url: 'https://courts.mt.gov/selfhelp/small-claims', legal_aid_url: 'https://www.montanalawhelp.org/', ag_complaint_url: 'https://dojmt.gov/consumer/' },
  NE: { name: 'Nebraska', deposit_statute: 'Neb. Rev. Stat. §76-1416', deposit_statute_url: 'https://nebraskalegislature.gov/', small_claims_url: 'https://supremecourt.nebraska.gov/self-help/small-claims', legal_aid_url: 'https://www.nebraskalegalaid.org/', ag_complaint_url: 'https://ago.nebraska.gov/' },
  NV: { name: 'Nevada', deposit_statute: 'Nev. Rev. Stat. §118A.242', deposit_statute_url: 'https://www.leg.state.nv.us/', small_claims_url: 'https://www.civillawselfhelpcenter.org/self-help/small-claims', legal_aid_url: 'https://nevadalegalservices.org/', ag_complaint_url: 'https://ag.nv.gov/Complaints/File_Complaint/' },
  NH: { name: 'New Hampshire', deposit_statute: 'N.H. Rev. Stat. §540-A:7', deposit_statute_url: 'https://www.gencourt.state.nh.us/', small_claims_url: 'https://www.courts.nh.gov/self-help/small-claims', legal_aid_url: 'https://www.nhla.org/', ag_complaint_url: 'https://www.doj.nh.gov/consumer/complaints/' },
  NJ: { name: 'New Jersey', deposit_statute: 'N.J. Stat. §46:8-19 to 46:8-26', deposit_statute_url: 'https://lis.njleg.state.nj.us/', small_claims_url: 'https://www.njcourts.gov/self-help/small-claims', legal_aid_url: 'https://www.lsnj.org/', ag_complaint_url: 'https://www.njoag.gov/' },
  NM: { name: 'New Mexico', deposit_statute: 'N.M. Stat. §47-8-18', deposit_statute_url: 'https://nmonesource.com/', small_claims_url: 'https://www.nmcourts.gov/self-help/small-claims/', legal_aid_url: 'https://www.lawhelpnewmexico.org/', ag_complaint_url: 'https://www.nmag.gov/consumer/file-a-complaint/' },
  NC: { name: 'North Carolina', deposit_statute: 'N.C. Gen. Stat. §42-50 to 42-56', deposit_statute_url: 'https://www.ncleg.gov/', small_claims_url: 'https://www.nccourts.gov/help-topics/lawsuits-and-claims/small-claims', legal_aid_url: 'https://www.legalaidnc.org/', ag_complaint_url: 'https://ncdoj.gov/file-a-complaint/' },
  ND: { name: 'North Dakota', deposit_statute: 'N.D. Cent. Code §47-16-07.1', deposit_statute_url: 'https://www.ndlegis.gov/', small_claims_url: 'https://www.ndcourts.gov/legal-self-help/small-claims', legal_aid_url: 'https://www.legalassist.nd.gov/', ag_complaint_url: 'https://attorneygeneral.nd.gov/consumer-protection/file-complaint' },
  OH: { name: 'Ohio', deposit_statute: 'Ohio Rev. Code §5321.16', deposit_statute_url: 'https://codes.ohio.gov/ohio-revised-code/section-5321.16', small_claims_url: 'https://www.supremecourt.ohio.gov/', legal_aid_url: 'https://www.ohiolegalhelp.org/', ag_complaint_url: 'https://www.ohioattorneygeneral.gov/' },
  OK: { name: 'Oklahoma', deposit_statute: 'Okla. Stat. tit. 41, §115', deposit_statute_url: 'https://www.oscn.net/', small_claims_url: 'https://www.oscn.net/static/forms/aoc_forms/smallclaims.asp', legal_aid_url: 'https://www.legalaidok.org/', ag_complaint_url: 'https://www.oag.ok.gov/consumer-protection/file-a-complaint' },
  OR: { name: 'Oregon', deposit_statute: 'Or. Rev. Stat. §90.300', deposit_statute_url: 'https://www.oregonlegislature.gov/', small_claims_url: 'https://www.courts.oregon.gov/programs/smallclaims/', legal_aid_url: 'https://oregonlawhelp.org/', ag_complaint_url: 'https://www.doj.state.or.us/consumer-protection/' },
  PA: { name: 'Pennsylvania', deposit_statute: '68 Pa. Stat. §250.511a-250.512', deposit_statute_url: 'https://www.legis.state.pa.us/', small_claims_url: 'https://www.pacourts.us/', legal_aid_url: 'https://palegalaid.net/', ag_complaint_url: 'https://www.attorneygeneral.gov/submit-a-complaint/' },
  RI: { name: 'Rhode Island', deposit_statute: 'R.I. Gen. Laws §34-18-19', deposit_statute_url: 'http://webserver.rilin.state.ri.us/', small_claims_url: 'https://www.courts.ri.gov/', legal_aid_url: 'https://www.helprilaw.org/', ag_complaint_url: 'https://riag.ri.gov/consumer-protection/file-complaint' },
  SC: { name: 'South Carolina', deposit_statute: 'S.C. Code §27-40-410', deposit_statute_url: 'https://www.scstatehouse.gov/', small_claims_url: 'https://www.sccourts.org/', legal_aid_url: 'https://www.lawhelp.org/sc/', ag_complaint_url: 'https://consumer.sc.gov/file-a-complaint' },
  SD: { name: 'South Dakota', deposit_statute: 'S.D. Codified Laws §43-32-6.1', deposit_statute_url: 'https://sdlegislature.gov/', small_claims_url: 'https://ujs.sd.gov/smallclaims/', legal_aid_url: 'https://www.sdlawhelp.org/', ag_complaint_url: 'https://consumer.sd.gov/complaints.aspx' },
  TN: { name: 'Tennessee', deposit_statute: 'Tenn. Code §66-28-301', deposit_statute_url: 'https://www.tn.gov/', small_claims_url: 'https://www.tncourts.gov/', legal_aid_url: 'https://www.las.org/', ag_complaint_url: 'https://www.tn.gov/attorneygeneral/' },
  UT: { name: 'Utah', deposit_statute: 'Utah Code §57-17-3', deposit_statute_url: 'https://le.utah.gov/', small_claims_url: 'https://www.utcourts.gov/', legal_aid_url: 'https://www.utahlegalservices.org/', ag_complaint_url: 'https://www.attorneygeneral.utah.gov/contact/complaint-form/' },
  VT: { name: 'Vermont', deposit_statute: 'Vt. Stat. tit. 9, §4461', deposit_statute_url: 'https://legislature.vermont.gov/', small_claims_url: 'https://www.vermontjudiciary.org/self-help/small-claims', legal_aid_url: 'https://www.vtlegalaid.org/', ag_complaint_url: 'https://ago.vermont.gov/consumer-protection/file-consumer-complaint' },
  VA: { name: 'Virginia', deposit_statute: 'Va. Code §55.1-1226', deposit_statute_url: 'https://law.lis.virginia.gov/', small_claims_url: 'https://www.vacourts.gov/', legal_aid_url: 'https://www.valegalaid.org/', ag_complaint_url: 'https://www.oag.state.va.us/consumer-protection/' },
  WA: { name: 'Washington', deposit_statute: 'Wash. Rev. Code §59.18.280', deposit_statute_url: 'https://app.leg.wa.gov/', small_claims_url: 'https://www.courts.wa.gov/', legal_aid_url: 'https://www.washingtonlawhelp.org/', ag_complaint_url: 'https://www.atg.wa.gov/file-complaint' },
  WV: { name: 'West Virginia', deposit_statute: 'W. Va. Code §37-6A-1', deposit_statute_url: 'https://www.wvlegislature.gov/', small_claims_url: 'https://www.courtswv.gov/', legal_aid_url: 'https://www.lawv.net/', ag_complaint_url: 'https://www.ago.wv.gov/consumerprotection/' },
  WI: { name: 'Wisconsin', deposit_statute: 'Wis. Stat. §704.28', deposit_statute_url: 'https://docs.legis.wisconsin.gov/', small_claims_url: 'https://www.wicourts.gov/', legal_aid_url: 'https://www.legalaction.org/', ag_complaint_url: 'https://datcp.wi.gov/' },
  WY: { name: 'Wyoming', deposit_statute: 'Wyo. Stat. §1-21-1207 to 1-21-1208', deposit_statute_url: 'https://wyoleg.gov/', small_claims_url: 'https://www.courts.state.wy.us/', legal_aid_url: 'https://www.lawyoming.org/', ag_complaint_url: 'https://www.ag.wyo.gov/' },
};
