import Link from 'next/link';
import { ArrowRight, Scale, Clock, FileText, MapPin } from 'lucide-react';

import { safeJsonLd } from '@/lib/safe-json-ld';
import { JURISDICTIONS, shippableCounties } from '@/lib/seo/config';
import { DEPOSIT_FAQS } from '@/lib/seo/deposit-faqs';
import {
  breadcrumbSchema,
  depositServiceSchema,
  organizationSchema,
  websiteSchema,
} from '@/lib/seo/schema';

interface DepositStatePageProps {
  stateCode: string;
  stateName: string;
  returnDeadline: string;
  primaryStatute: string;
  statuteSummary: string;
  penaltyNote: string;
}

export function DepositStatePage({
  stateCode,
  stateName,
  returnDeadline,
  primaryStatute,
  statuteSummary,
  penaltyNote,
}: DepositStatePageProps) {
  const jurisdiction = JURISDICTIONS.find((j) => j.code === stateCode);
  const counties = jurisdiction ? shippableCounties(jurisdiction) : [];
  const statePath = jurisdiction?.page.path ?? `/deposit/${stateName.toLowerCase()}`;
  const faqs = DEPOSIT_FAQS[stateCode] ?? [];

  const breadcrumb = breadcrumbSchema([
    { name: 'Home', path: '/' },
    { name: 'Security Deposit', path: '/deposit' },
    { name: stateName, path: statePath },
  ]);
  const service = depositServiceSchema({ stateName, path: statePath });

  return (
    <main className="min-h-screen bg-white">
      {/* Hero */}
      <section className="mx-auto max-w-4xl px-6 py-20">
        <Link
          href="/deposit"
          className="text-sm text-neutral-500 hover:text-neutral-700"
        >
          All States
        </Link>

        <h1 className="mt-4 text-4xl font-bold tracking-tight text-neutral-900 sm:text-5xl">
          {stateName} Security Deposit Recovery
        </h1>
        <p className="mt-6 max-w-2xl text-lg text-neutral-600">
          Draft a demand letter grounded in {stateName} landlord-tenant law.
          Cited, validated, and ready to send to your former landlord.
        </p>

        <div className="mt-8">
          <Link
            href="/new?wedge=deposit"
            className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-neutral-800"
          >
            Start Your {stateCode} Letter
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </section>

      {/* Key facts */}
      <section className="border-t border-neutral-100 bg-neutral-50 py-16">
        <div className="mx-auto max-w-4xl px-6">
          <h2 className="text-2xl font-bold text-neutral-900">
            {stateName} Deposit Law at a Glance
          </h2>
          <div className="mt-8 grid gap-6 sm:grid-cols-3">
            <div className="rounded-lg border border-neutral-200 bg-white p-5">
              <Scale className="h-6 w-6 text-neutral-600" />
              <h3 className="mt-3 font-semibold text-neutral-900">
                Primary Statute
              </h3>
              <p className="mt-1 text-sm text-neutral-600">{primaryStatute}</p>
            </div>
            <div className="rounded-lg border border-neutral-200 bg-white p-5">
              <Clock className="h-6 w-6 text-neutral-600" />
              <h3 className="mt-3 font-semibold text-neutral-900">
                Return Deadline
              </h3>
              <p className="mt-1 text-sm text-neutral-600">{returnDeadline}</p>
            </div>
            <div className="rounded-lg border border-neutral-200 bg-white p-5">
              <FileText className="h-6 w-6 text-neutral-600" />
              <h3 className="mt-3 font-semibold text-neutral-900">Penalty</h3>
              <p className="mt-1 text-sm text-neutral-600">{penaltyNote}</p>
            </div>
          </div>
        </div>
      </section>

      {/* What the statute provides */}
      <section className="py-16">
        <div className="mx-auto max-w-4xl px-6">
          <h2 className="text-2xl font-bold text-neutral-900">
            What {primaryStatute} Provides
          </h2>
          <p className="mt-4 text-neutral-600 leading-relaxed">
            {statuteSummary}
          </p>
          <p className="mt-4 text-sm text-neutral-500">
            This is general information about the statute. A demand letter
            generated by Resolvaio will cite the specific subsections relevant to
            your situation. Verify current law with official sources.
          </p>
        </div>
      </section>

      {/* How it works */}
      <section className="border-t border-neutral-100 bg-neutral-50 py-16">
        <div className="mx-auto max-w-4xl px-6">
          <h2 className="text-2xl font-bold text-neutral-900">
            How to Recover Your Deposit in {stateName}
          </h2>
          <ol className="mt-8 space-y-4 text-neutral-700">
            <li className="flex gap-3">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-neutral-200 text-sm font-bold">
                1
              </span>
              <span>
                <strong>Answer diagnostic questions</strong> about your tenancy,
                move-out date, deposit amount, and any deductions claimed.
              </span>
            </li>
            <li className="flex gap-3">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-neutral-200 text-sm font-bold">
                2
              </span>
              <span>
                <strong>Receive a demand letter</strong> citing {primaryStatute}{' '}
                and other applicable {stateName} statutes.
              </span>
            </li>
            <li className="flex gap-3">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-neutral-200 text-sm font-bold">
                3
              </span>
              <span>
                <strong>Review and send</strong> via USPS Certified Mail with
                Return Receipt. We track the statutory deadline.
              </span>
            </li>
            <li className="flex gap-3">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-neutral-200 text-sm font-bold">
                4
              </span>
              <span>
                <strong>If no response</strong>, escalation documents for small
                claims court or a state attorney general complaint are available.
              </span>
            </li>
          </ol>
          <div className="mt-8">
            <Link
              href="/new?wedge=deposit"
              className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-neutral-800"
            >
              Get Started — $49
              <ArrowRight className="h-4 w-4" />
            </Link>
            <p className="mt-2 text-xs text-neutral-500">
              Refund available before generation. One letter per case.
            </p>
          </div>
        </div>
      </section>

      {/* Counties — internal links to the per-county pages (only verified ones ship) */}
      {counties.length > 0 && (
        <section className="py-16">
          <div className="mx-auto max-w-4xl px-6">
            <h2 className="text-2xl font-bold text-neutral-900">
              {stateName} small claims by county
            </h2>
            <p className="mt-3 text-neutral-600">
              If your landlord ignores the demand letter, here&apos;s where you file
              in {stateName} — with each county&apos;s court and filing fee.
            </p>
            <ul className="mt-8 grid gap-4 sm:grid-cols-2">
              {counties.map((c) => (
                <li key={c.slug}>
                  <Link
                    href={`${statePath}/${c.slug}`}
                    className="flex items-start gap-3 rounded-lg border border-neutral-200 p-4 transition-colors hover:border-primary/40 hover:bg-neutral-50"
                  >
                    <MapPin className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
                    <span>
                      <span className="block font-semibold text-neutral-900">{c.name}</span>
                      <span className="mt-0.5 block text-sm text-neutral-500">{c.filingFee}</span>
                    </span>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </section>
      )}

      {/* FAQ — visible Q&A copy targeting "People Also Ask" / AI Overviews.
          Answers are statute-cited and drawn from the same verified facts as the
          KB and the demand-letter generator. No FAQPage schema (retired for rich
          results); the visible copy is what AI search extracts. */}
      {faqs.length > 0 && (
        <section className="border-t border-neutral-100 bg-neutral-50 py-16">
          <div className="mx-auto max-w-3xl px-6">
            <h2 className="text-2xl font-bold text-neutral-900">
              {stateName} security deposit — common questions
            </h2>
            <dl className="mt-8 space-y-6">
              {faqs.map((faq) => (
                <div
                  key={faq.question}
                  className="rounded-lg border border-neutral-200 bg-white p-5"
                >
                  <dt className="font-semibold text-neutral-900">{faq.question}</dt>
                  <dd className="mt-2 text-neutral-600 leading-relaxed">
                    {faq.answer}
                  </dd>
                </div>
              ))}
            </dl>
            <p className="mt-6 text-xs text-neutral-500">
              General information about {stateName} law. Resolvaio is a writing
              and research assistance tool, not a law firm. Verify current
              statutes with official sources before acting.
            </p>
          </div>
        </section>
      )}

      {/* JSON-LD structured data — all derived from seo/config (single source of
          truth), so it can't drift from the visible page or hardcode the domain. */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(organizationSchema()) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(websiteSchema()) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(service) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(breadcrumb) }} />

      {/* Disclaimer */}
      <footer className="border-t border-neutral-100 py-8">
        <p className="mx-auto max-w-2xl px-6 text-center text-xs text-neutral-500">
          Resolvaio is a writing assistance tool. It does not provide legal
          advice, does not evaluate cases, and does not guarantee outcomes.
          Generated letters should be reviewed before use. Consider consulting a
          licensed attorney for advice about your specific situation.
        </p>
        <div className="mt-4 flex flex-wrap justify-center gap-x-4 gap-y-1 px-6 text-xs text-neutral-400">
          <Link href="/legal/terms" className="transition-colors hover:text-neutral-700">Terms</Link>
          <Link href="/legal/privacy" className="transition-colors hover:text-neutral-700">Privacy</Link>
          <Link href="/legal/cookies" className="transition-colors hover:text-neutral-700">Cookies</Link>
          <Link href="/legal/acceptable-use" className="transition-colors hover:text-neutral-700">Acceptable Use</Link>
          <Link href="/legal/ai-disclosure" className="transition-colors hover:text-neutral-700">AI Disclosure</Link>
          <Link href="/legal/accessibility" className="transition-colors hover:text-neutral-700">Accessibility</Link>
        </div>
        <p className="mt-4 text-center text-xs text-neutral-400">
          &copy; {new Date().getFullYear()} Resolvaio. All rights reserved.
          Resolvaio is owned and operated by Nikola Innovations Limited.
        </p>
      </footer>
    </main>
  );
}
